
--月度项目计划表
DROP TABLE IF EXISTS `T_PROJECT_SCHEDULE`;
CREATE TABLE T_PROJECT_SCHEDULE(
	TPS_PROJECT_ID CHAR(4) NOT NULL COMMENT '項目編號',
	TPS_YEAR VARCHAR(12) NOT NULL COMMENT '年份',
	TPS_MONTH CHAR(2) NOT NULL COMMENT '月份',
	TPS_MONTH_FINISHED CHAR(2) NOT NULL COMMENT '是否完成標誌 00-未完成，01-已完成，默认为00',
	TPS_FINISH_DETAIL VARCHAR(300) COMMENT '月度完成情況說明',
	TPS_REMARKS VARCHAR(300) COMMENT '备注',
    PRIMARY KEY (`TPS_PROJECT_ID`,`TPS_YEAR`,`TPS_MONTH`),
  	FOREIGN KEY (`TPS_PROJECT_ID`) REFERENCES T_PROJECT_INFO(`TPI_PROJECT_ID`)
);

--项目详细信息表
DROP TABLE IF EXISTS `T_PROJECT_INFO`;
CREATE TABLE T_PROJECT_INFO(
  TPI_PROJECT_ID CHAR(4) COMMENT '项目编号',
  TPI_PROJECT_NAME VARCHAR(200) NOT NULL COMMENT '项目名称',
  TPI_PROJECT_SUMMARY VARCHAR(300) COMMENT '项目简介',
  TPI_CREATE_DATE DATE NOT NULL COMMENT '项目创建日期',
  TPI_CREATE_PERSON VARCHAR(200) COMMENT '-录入人',
  TPI_PROJECT_LEADER VARCHAR(200) NOT NULL COMMENT '项目负责人姓名',
  TPI_VALIDATE CHAR(1) DEFAULT 'Y' NOT NULL COMMENT '是否有效,默认为Y有效',
  TPI_ATTACHMENT_URL VARCHAR(120) COMMENT '附件地址',
  TPI_ANNUAL_SCH_STATEMENT VARCHAR(300) COMMENT '项目年度计划说明',
  TPI_REMARK VARCHAR(300) COMMENT '备注',
  PRIMARY KEY (`TPI_PROJECT_ID`),
  FOREIGN KEY (`TPI_PROJECT_ID`) REFERENCES T_PROJECT_CODE(`TPS_PROJECT_ID`)
);

ALTER TABLE T_PROJECT_SCHEDULE COMMENT='月度詳細計劃表';

ALTER TABLE T_PROJECT_INFO COMMENT='項目詳細信息表';

